# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  docker: circleci/docker@2.2.0
jobs:
   build-and-push:
    environment:
     DOCKER_IMAGE: lodaidelima/musicapp
     DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout    
      - docker/check
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
   deploy:
    executor: docker/docker
    steps: 
      - add_ssh_keys: 
          fingerprints: 
            - "ca:ed:2c:49:88:5b:67:67:01:2e:21:f5:00:92:6d:98"
      - run: ssh -i %USERPROFILE%/.ssh/lodai -oStrictHostKeyChecking=no -v lodai@mrtoapp.click './deploy.sh'
workflows:
  automation: 
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: npm
      - build-and-push:
          requires:
            - node/test
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build-and-push



